name: CI

on:
    push:
        branches:
            - master
        paths-ignore:
            - 'README.md'
            - 'helm/**'

jobs:

    build:
        # A virtual container where github will run this stage
        runs-on: ubuntu-latest
        
        steps:
        - name: checkout the repository
          uses: actions/checkout@v4

        - name: Set up Go 1.24
          uses: actions/setup-go@v2
          with: 
            go-version: 1.24

        - name: Build
          run: go build -o main .

        - name: Test
          run: go test ./...
    
    code-quality:
        runs-on: ubuntu-latest

        steps:
            - name: checkout the repository
              uses: actions/checkout@v4

            - name: Run golangci-lint
              uses: golangci/golangci-lint-action@v6
              with:
                version: v1.56.2
              continue-on-error: true

    push:
        runs-on: ubuntu-latest

        needs: build

        steps:

           - name: Checkout the repository
             uses: actions/checkout@v4
         
           - name: Set up Docker Buildx
             uses: docker/setup-buildx-action@v3
           
           - name: Login to Docker Hub
             uses: docker/login-action@v3
             with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
      
          
        
           - name: Build and push
             uses: docker/build-push-action@v6
             with:
                context: .
                file: ./Dockerfile
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/go-web-app:${{github.run_id}}

    update-tag-in-helm-chart:
        runs-on: ubuntu-latest

        needs: push

        steps:
            - name: Checkout the repository
              uses: actions/checkout@v4
              with:
                token: ${{ secrets.TOKEN }}

            - name: Update Helm chart version
              run: |
               sed -i 's/tag: .*/tag: "${{github.run_id}}/"' helm/go-web-app-chart/values.yaml

            - name: Commit and push changes
              run: |
                git config --global user.email "biggieest@gmail.com"
                git config --global user.name "otie16"
                git add helm/go-web-app-chart/values.yaml
                git commit -m "Update image tag in helm chart"
                git push